import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Sparkles, Target, FileSearch, Zap } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "ATS Lens — AI Resume Optimizer that beats ATS filters" },
      {
        name: "description",
        content:
          "Upload your resume and a job description to get an instant AI-powered ATS match score, missing keywords, and tailored bullet rewrites.",
      },
      { property: "og:title", content: "ATS Lens — Beat the bots. Land the interview." },
      {
        property: "og:description",
        content:
          "Instant ATS match score, missing keywords, and AI-tailored bullet rewrites for your resume.",
      },
      { property: "og:url", content: "https://ai-resume-analyzer111.lovable.app/" },
    ],
    links: [{ rel: "canonical", href: "https://ai-resume-analyzer111.lovable.app/" }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "SoftwareApplication",
          name: "ATS Lens",
          applicationCategory: "BusinessApplication",
          operatingSystem: "Web",
          url: "https://ai-resume-analyzer111.lovable.app/",
          description:
            "AI Resume ATS Analyzer that scores resumes against job descriptions and generates tailored bullet rewrites.",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        }),
      },
    ],
  }),
  component: Landing,
});

function Landing() {
  return (
    <div className="min-h-screen bg-background bg-mesh">
      <header className="container mx-auto flex items-center justify-between px-6 py-6">
        <div className="flex items-center gap-2">
          <div className="grid size-9 place-items-center rounded-lg bg-gradient-primary shadow-glow">
            <Sparkles className="size-5 text-primary-foreground" />
          </div>
          <span className="font-display text-lg font-semibold">ATS Lens</span>
        </div>
        <Link to="/auth">
          <Button variant="ghost">Sign in</Button>
        </Link>
      </header>

      <main className="container mx-auto px-6 pb-24 pt-12 md:pt-24">
        <section className="mx-auto max-w-3xl text-center">
          <div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card/40 px-4 py-1.5 text-xs text-muted-foreground">
            <span className="size-1.5 rounded-full bg-success" />
            AI-powered resume optimization
          </div>
          <h1 className="text-balance font-display text-5xl font-bold leading-[1.05] md:text-7xl">
            Beat the bots.<br />
            <span className="text-gradient">Land the interview.</span>
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-balance text-base text-muted-foreground md:text-lg">
            Upload your resume and a job description. Get an instant ATS match score, the keywords
            you're missing, and tailored bullet rewrites — generated by AI.
          </p>
          <div className="mt-10 flex flex-wrap justify-center gap-3">
            <Link to="/auth">
              <Button size="lg" className="bg-gradient-primary text-primary-foreground shadow-glow hover:opacity-90">
                Analyze my resume
              </Button>
            </Link>
            <Link to="/auth">
              <Button size="lg" variant="outline">
                Sign in
              </Button>
            </Link>
          </div>
        </section>

        <section className="mx-auto mt-24 grid max-w-5xl gap-4 md:grid-cols-3">
          {[
            { icon: Target, title: "ATS Match Score", body: "Quantified keyword overlap between your resume and the JD." },
            { icon: FileSearch, title: "Skill Gap Analysis", body: "See exactly which required skills are missing or weak." },
            { icon: Zap, title: "Tailored Rewrites", body: "AI-rewritten bullets with action verbs and quantified impact." },
          ].map((f) => (
            <div key={f.title} className="glass rounded-2xl p-6 shadow-card">
              <div className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary">
                <f.icon className="size-5" />
              </div>
              <h2 className="mt-4 font-display text-lg font-semibold">{f.title}</h2>
              <p className="mt-1 text-sm text-muted-foreground">{f.body}</p>
            </div>
          ))}
        </section>
      </main>
    </div>
  );
}
